"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "fr" | "nl" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
    fr: {
      // Navigation
      "nav.home": "Accueil",
      "nav.about": "À propos",
      "nav.services": "Services",
      "nav.portfolio": "Portfolio",
      "nav.contact": "Contact",
      "nav.quote": "Devis gratuit",
      
      // Hero
      "hero.badge": "Guapo Web Designer",
    "hero.title": "If you can imagine it, we can",
    "hero.title.highlight": "design it.",
    "hero.subtitle": "Des sites web conçus pour améliorer votre visibilité et professionnaliser votre entreprise",
    "hero.cta.projects": "Voir nos projets",
    "hero.cta.contact": "Nous contacter",
    
      // Announcement Banner
      "announcement.offer": "",
      "announcement.subtitle": "",
      
      // About
    "about.title": "À propos de Guapo",
    "about.values.passion": "Passion",
    "about.values.passion.desc": "Chaque projet est une nouvelle aventure créative",
    "about.values.innovation": "Innovation",
    "about.values.innovation.desc": "Toujours à l'avant-garde des tendances",
    "about.values.performance": "Performance",
    "about.values.performance.desc": "Des sites rapides et optimisés",
    "about.values.creativity": "Créativité",
    "about.values.creativity.desc": "Des designs uniques et mémorables",
    "about.heading": "Créateur passionné",
    "about.intro": "Passionnés par le design et les nouvelles technologies, nous créons des sites web modernes, élégants et performants. Notre approche combine créativité, expertise technique et attention aux détails pour donner vie à vos projets digitaux.",
    "about.p1": "Chaque projet est unique et mérite une attention particulière.",
    "about.badge.design": "🎨 Design UI/UX",
    "about.badge.performance": "⚡ Performance optimale",
    "about.badge.tech": "🚀 Technologies modernes",
    
    // Services - Website Cards Section
    "services.website.title.prefix": "Besoin d'un",
    "services.website.title.highlight": "Site Web",
    "services.website.subtitle": "Choisissez la solution adaptée à vos besoins",
    "services.website.showcase.title": "Site Vitrine",
    "services.website.showcase.desc": "Site professionnel pour présenter votre entreprise, vos services et votre expertise. Idéal pour restaurants, cabinets, PME et portfolios.",
    "services.website.ecommerce.title": "Site E-commerce",
    "services.website.ecommerce.desc": "Vendez vos produits en ligne avec une boutique professionnelle et sécurisée. Gestion des commandes, paiements en ligne, suivi des stocks.",
    "services.website.discuss.title": "Discutons Ensemble",
    "services.website.discuss.desc": "Vous avez un projet sur mesure ou des besoins spécifiques ? Contactez-nous pour en discuter et trouver la meilleure solution ensemble.",
    "services.website.discuss.cta": "Nous contacter",
    "services.website.cta": "Obtenir un devis",
    
    // Services Page
    "services.page.title": "Nos Services",
    "services.desktop.title": "Sites Vitrine Desktop",
    "services.desktop.desc": "Sites web optimisés pour écrans larges avec designs professionnels et modernes",
    "services.tablet.title": "Adaptation Tablette",
    "services.tablet.desc": "Interfaces parfaitement adaptées aux tablettes pour une expérience fluide",
    "services.mobile.title": "Optimisation Mobile",
    "services.mobile.desc": "Navigation optimale sur smartphones avec performances maximales",
    "services.responsive.title": "Design Responsive",
    "services.responsive.desc": "Adaptation automatique à tous types d'appareils et résolutions",
    "services.branding.title": "Identité Visuelle",
    "services.branding.desc": "Création de logos, chartes graphiques et éléments visuels uniques",
    "services.performance.title": "Performance Web",
    "services.performance.desc": "Sites ultra-rapides optimisés pour le référencement et l'expérience utilisateur",
    "services.cta.title": "Besoin d'un site vitrine ? 🚀",
    "services.cta.desc": "Restaurant, cabinet professionnel, entreprise ou portfolio personnel : nous créons votre site vitrine accessible sur tous les appareils !",
    "services.cta.button": "Discutons de votre projet 💬",
    
    // Services
    "services.title": "Nos",
    "services.title.highlight": "Services",
    "services.subtitle": "Ce que nous pouvons faire pour vous",
    "services.design.title": "Design UI/UX",
    "services.design.desc": "Création d'interfaces utilisateur intuitives et attrayantes avec une expérience optimale.",
    "services.dev.title": "Développement Web",
    "services.dev.desc": "Développement de sites web modernes avec React, Next.js et les dernières technologies.",
    
    // Portfolio
    "portfolio.title.prefix": "Port",
    "portfolio.title.highlight": "folio",
    "portfolio.subtitle": "Nos projets récents",
    
    // Contact Section
    "contact.section.title": "Contactez-nous",
    "contact.section.subtitle": "Transformons vos idées en réalité digitale",
    "contact.section.desc": "Un projet en tête ? N'hésitez pas à nous contacter pour en discuter. Nous serons ravis de vous accompagner dans la création de votre site web.",
    "contact.quote.title": "Devis Gratuit",
    "contact.quote.desc": "Obtenez une estimation",
    
    // Contact Page
    "contact.page.title": "Contactez-nous",
    "contact.page.intro": "Besoin d'un site web moderne et performant ? Contactez-nous dès maintenant !",
    "contact.email.title": "Email",
    "contact.email.address": "info@guapowebdesigner.com",
    "contact.email.copy": "Copier",
    "contact.email.copied": "Email copié !",
    "contact.instagram.title": "Instagram",
    "contact.instagram.handle": "@guapo.webdesigner",
    "contact.instagram.copy": "Copier",
    "contact.instagram.copied": "Handle copié !",
    "contact.form.title": "Demande de devis",
    "contact.form.name": "Nom complet",
    "contact.form.email": "Email",
    "contact.form.phone": "Téléphone (optionnel)",
    "contact.form.message": "Message",
    "contact.form.submit": "Envoyer la demande",
    "contact.form.sending": "Envoi en cours...",
    "contact.form.success": "Demande envoyée avec succès !",
    "contact.form.error": "Erreur lors de l'envoi. Veuillez réessayer.",
    
    // Quote Page
    "quote.page.badge": "Devis gratuit sous 48h",
    "quote.page.title": "Demande de",
    "quote.page.title.highlight": "Devis",
    "quote.page.subtitle": "Parlez-nous de votre projet et recevez un devis personnalisé adapté à vos besoins et votre budget.",
    "quote.page.card1.title": "Réponse rapide",
    "quote.page.card1.desc": "Devis sous 48h maximum",
    "quote.page.card2.title": "Devis gratuit",
    "quote.page.card2.desc": "Sans engagement",
    "quote.page.card3.title": "Sur mesure",
    "quote.page.card3.desc": "Adapté à vos besoins",
    "quote.page.cta.title": "Des questions avant de faire votre demande ?",
    "quote.page.cta.desc": "N'hésitez pas à nous contacter directement par email ou sur Instagram",
    
    // Quote Form - Step 1: Type Selection
    "quote.type.title": "Quel type de projet souhaitez-vous ?",
    "quote.type.subtitle": "Choisissez le type de site qui correspond à vos besoins",
    "quote.type.showcase": "Site Vitrine",
    "quote.type.showcase.desc": "Site web de présentation pour votre entreprise, portfolio, ou activité professionnelle",
    "quote.type.showcase.feature1": "Présentation d'entreprise",
    "quote.type.showcase.feature2": "Portfolio professionnel",
    "quote.type.showcase.feature3": "Formulaires de contact",
    "quote.type.showcase.feature4": "Design sur-mesure",
    "quote.type.ecommerce": "Site E-commerce",
    "quote.type.ecommerce.desc": "Boutique en ligne complète pour vendre vos produits ou services sur internet",
    "quote.type.ecommerce.feature1": "Catalogue produits",
    "quote.type.ecommerce.feature2": "Panier & paiement en ligne",
    "quote.type.ecommerce.feature3": "Gestion des commandes",
    "quote.type.ecommerce.feature4": "Comptes clients",
    "quote.type.menu": "Menu / Site de commande",
    "quote.type.menu.desc": "Site de commande pour restaurant avec menu digital, QR code et gestion des commandes en temps réel",
    "quote.type.menu.feature1": "Système de base",
    "quote.type.menu.feature2": "Catégories et plats",
    "quote.type.menu.feature3": "Responsive mobile optimisé",
    "quote.type.menu.feature4": "Design restaurant",
    "quote.menu.base.title": "Système de base",
    "quote.menu.base.name": "Système de base",
    "quote.menu.base.desc": "menu cliquable, catégories et plats responsive mobile et design optimisé restaurant",
    "quote.menu.restaurantFeatures": "Fonctionnalités Restaurant",
        "quote.menu.resto.kitchen": "Dashboard Cuisine",
          "quote.menu.resto.kitchen.desc": "Interface dédiée pour la cuisine : réception et gestion des commandes en temps réel",
          "quote.menu.resto.status": "Statuts de commande cuisine",
          "quote.menu.resto.status.desc": "Marquer les plats comme 'en préparation', 'prêts' ou 'servis'",
          "quote.menu.resto.stock": "Gestion des stocks",
          "quote.menu.resto.stock.desc": "Désactiver un plat du menu en un clic s'il est épuisé",
          "quote.menu.resto.waiter": "Dashboard Serveur",
          "quote.menu.resto.waiter.desc": "Interface pour les serveurs : suivi des commandes et appels clients",
          "quote.menu.resto.waiterStatus": "Statuts de commande serveur",
          "quote.menu.resto.waiterStatus.desc": "Suivi du cycle de vie des commandes par table",
          "quote.menu.resto.menuManagement": "Gestion du menu",
          "quote.menu.resto.menuManagement.desc": "Interface d'administration pour modifier vos plats et prix en autonomie",
        "quote.menu.subscription.title": "Choisissez votre pack de gestion menu",
          "quote.menu.subscription.simple.name": "Pack Menu Simple",
          "quote.menu.subscription.simple.desc": "Ajouter, supprimer et modifier vos plats en toute simplicité",
          "quote.menu.subscription.complete.name": "Pack Menu Complet",
            "quote.menu.subscription.complete.desc": "Simple Pack + création de plusieurs menus (Saison, Fêtes, etc.)",
            "quote.menu.subscription.freeMonth": "",
            "quote.menu.clientFeatures": "Fonctionnalités Client",
        "quote.menu.client.cart": "Ajout au panier",
        "quote.menu.client.cart.desc": "Permettre aux clients de sélectionner leurs plats",
        "quote.menu.client.dineIn": "Sur place / à emporter",
        "quote.menu.client.dineIn.desc": "Choix du mode de consommation",
        "quote.menu.client.confirmation": "Confirmation de commande",
        "quote.menu.client.confirmation.desc": "Récapitulatif final avant validation",
        "quote.menu.client.email": "Email automatique client",
        "quote.menu.client.email.desc": "Envoi d'un reçu automatique par email au client",

    "quote.type.start": "Commencer",
    
    // Quote Form - Step 2: Questions
    "quote.back": "Retour au choix du type de projet",
    "quote.selected": "Type de projet sélectionné :",
    "quote.showcase.pages": "Nombre de pages du site vitrine",
    "quote.ecommerce.size": "Taille de votre boutique e-commerce",
    "quote.ecommerce.small": "Petite boutique (1-20 produits)",
    "quote.ecommerce.small.desc": "Idéal pour démarrer avec une sélection limitée",
    "quote.ecommerce.medium": "Boutique moyenne (21-100 produits)",
    "quote.ecommerce.medium.desc": "Pour une gamme de produits diversifiée",
    "quote.ecommerce.large": "Grande boutique (100+ produits)",
      "quote.ecommerce.large.desc": "Catalogue complet avec gestion avancée",
      "quote.ecommerce.note": "Nos prix sont sur demande et adaptés à votre projet",
      "quote.selected.label": "Type sélectionné :",
    "quote.selected.size": "Taille sélectionnée :",
    "quote.modify": "Modifier",
    "quote.features.ecommerce": "Fonctionnalités E-commerce",
    "quote.optimization.pack": "Pack Tout Inclus",
    "quote.optimization.pack.desc": "Inclut toutes les optimisations essentielles pour un site professionnel et performant",
    "quote.optimization.pack.seo": "SEO de base",
    "quote.optimization.pack.performance": "Optimisation vitesse",
    "quote.optimization.pack.ssl": "Certificat SSL/HTTPS",
    "quote.optimization.pack.gdpr": "Conformité RGPD",
    "quote.optimization.recommended": "⭐ RECOMMANDÉ",
    "quote.optimization.or": "ou choisissez individuellement",
    "quote.hosting.auto": "L'hébergement est automatiquement inclus dans votre projet.",
    
    // Quote Form
    "quote.success.title": "Merci pour votre demande !",
    "quote.info.title": "Informations",
    "quote.info.firstName": "Prénom",
    "quote.info.firstNamePlaceholder": "Votre prénom",
    "quote.info.lastName": "Nom",
    "quote.info.lastNamePlaceholder": "Votre nom",
    "quote.info.email": "Email",
    "quote.info.emailPlaceholder": "votre@email.com",
    "quote.info.company": "Nom de l'entreprise / Projet",
    "quote.info.companyPlaceholder": "Nom de votre entreprise ou projet",
    "quote.info.sector": "Secteur d'activité (facultatif)",
    "quote.info.sectorPlaceholder": "Ex: Restauration, Services, etc.",
    "quote.siteType.title": "Type de Site",
    "quote.siteType.simple": "Site vitrine simple (1 à 3 pages)",
    "quote.siteType.simpleDesc": "Idéal pour présenter votre activité avec les pages essentielles",
    "quote.siteType.standard": "Site vitrine standard (4 à 5 pages)",
    "quote.siteType.standardDesc": "Pour une présence web complète avec plus de contenu",
    "quote.siteType.advanced": "Site vitrine avancé (6 à 8 pages)",
    "quote.siteType.advancedDesc": "Pour une présentation détaillée de votre entreprise",
    "quote.siteType.premium": "Site vitrine premium (9 à 12 pages)",
    "quote.siteType.premiumDesc": "Pour un site complet avec toutes les informations nécessaires",
    "quote.siteType.portfolio": "Portfolio / site personnel",
    "quote.siteType.portfolioDesc": "Mettez en valeur vos réalisations et votre expertise",
    "quote.siteType.ecommerce": "Site e-commerce",
    "quote.siteType.ecommerceDesc": "Boutique en ligne complète avec gestion des produits et paiements",
    "quote.design.title": "Design & Contenu",
    "quote.design.custom": "Design sur mesure (UX/UI personnalisé) - Inclus",
    "quote.design.responsive": "Responsive (mobile + tablette + ordinateur) - Inclus",
    "quote.design.pageCount": "Nombre de pages prévues",
    "quote.design.pageCountPlaceholder": "Ex: 5",
    "quote.features.title": "Fonctionnalités / Modules",
    "quote.features.contactForm": "Formulaire de contact simple",
    "quote.features.quoteForm": "Formulaire de demande de devis",
    "quote.features.autoEmailsQuote": "Envoi automatique d'emails de confirmation (pour devis)",
    "quote.features.booking": "Système de prise de rendez-vous en ligne (avec emails automatiques)",
    "quote.features.calendar": "Ajouter au calendrier (Google Calendar, Outlook, ICS, etc.)",
    "quote.features.multilingual": "Multilingue",
    "quote.features.selectLanguages": "Sélectionnez les langues souhaitées :",
    "quote.features.otherLanguage": "Autre langue",
    "quote.features.otherLanguagePlaceholder": "Ex: Espagnol, Italien, Allemand...",
    "quote.features.productCatalog": "Catalogue de produits",
    "quote.features.shoppingCart": "Panier d'achat",
    "quote.features.paymentGateway": "Passerelle de paiement (Stripe, PayPal, etc.)",
    "quote.features.orderManagement": "Gestion des commandes",
    "quote.features.inventoryManagement": "Gestion des stocks",
    "quote.features.customerAccounts": "Comptes clients",
    "quote.optimization.title": "Optimisation & Sécurité",
    "quote.optimization.seo": "SEO de base (balises, titres, URLs)",
    "quote.optimization.performance": "Optimisation vitesse / performance",
    "quote.optimization.ssl": "Certificat SSL / HTTPS",
    "quote.optimization.gdpr": "RGPD / conformité légale",
    "quote.hosting.title": "Hébergement",
    "quote.hosting.hosting": "Hébergement",
    "quote.hosting.domain": "Nom de domaine",
    "quote.hosting.selectOption": "Sélectionnez une option",
    "quote.hosting.included": "Inclus dans le projet",
    "quote.hosting.clientProvided": "Fourni par le client",
    "quote.hosting.toDiscuss": "À discuter",
    "quote.message.title": "Remarques spécifiques / Besoins particuliers",
    "quote.message.label": "Description détaillée de votre projet",
    "quote.message.placeholder": "Décrivez votre projet en detail : vos objectifs, votre audience cible, vos besoins spécifiques, exemples de sites que vous aimez, contraintes particulières, etc.",
    "quote.gdpr.title": "Consentement RGPD",
    "quote.gdpr.text": "J'accepte que mes données personnelles soient collectées et traitées par GUAPO Web Designer dans le but de traiter ma demande de devis. Mes données ne seront jamais vendues à des tiers. Je peux exercer mes droits (accès, rectification, suppression) en contactant",
    "quote.gdpr.moreInfo": "Pour plus d'informations, consultez notre",
    "quote.gdpr.privacyPolicy": "politique de confidentialité",
    "quote.submit.button": "Envoyer ma demande de devis",
    "quote.submit.sending": "Envoi en cours...",
    "quote.submit.required": "* Champs obligatoires",
    
    // Legal Pages - Mentions Légales
    "legal.meta.title": "Mentions légales - GUAPO Web Designer",
    "legal.meta.description": "Mentions légales et informations juridiques du site GUAPO Web Designer",
    "legal.badge": "Informations légales",
    "legal.title": "Mentions",
    "legal.title.highlight": "Légales",
    "legal.subtitle": "Informations juridiques et éditeur du site",
    "legal.editor.title": "Éditeur du site",
    "legal.editor.company": "Raison sociale :",
    "legal.editor.website": "Site web :",
    "legal.editor.email": "Email :",
    "legal.editor.instagram": "Instagram :",
    "legal.host.title": "Hébergeur du site",
    "legal.host.name": "Nom :",
    "legal.host.address": "Adresse :",
    "legal.host.website": "Site web :",
    "legal.ip.title": "Propriété intellectuelle",
    "legal.ip.content1": "L'ensemble du contenu de ce site (textes, images, logos, design, structure) est la propriété exclusive de GUAPO Web Designer, sauf mention contraire.",
    "legal.ip.content2": "Toute reproduction, distribution, modification ou utilisation du contenu du site, en tout ou en partie, sans autorisation préalable écrite est strictement interdite et constitue une contrefaçon sanctionnée par les articles L.335-2 et suivants du Code de la propriété intellectuelle.",
    "legal.data.title": "Données personnelles",
    "legal.data.content1": "Le site guapowebdesigner.com respecte la vie privée de ses utilisateurs et s'engage à protéger les données personnelles collectées conformément au Règlement Général sur la Protection des Données (RGPD).",
    "legal.data.content2": "Pour en savoir plus sur la collecte et le traitement de vos données personnelles, consultez notre",
    "legal.data.link": "Politique de confidentialité",
    "legal.cookies.title": "Cookies",
    "legal.cookies.content1": "Ce site utilise des cookies pour améliorer l'expérience utilisateur et analyser le trafic. Vous pouvez accepter ou refuser les cookies non essentiels via la bannière de consentement.",
    "legal.cookies.content2": "Les cookies essentiels au fonctionnement du site sont automatiquement activés et ne peuvent pas être désactivés.",
    "legal.liability.title": "Limitation de responsabilité",
    "legal.liability.content1": "GUAPO Web Designer s'efforce d'assurer l'exactitude et la mise à jour des informations diffusées sur ce site, mais ne peut garantir l'exactitude, la précision ou l'exhaustivité des informations mises à disposition.",
    "legal.liability.content2": "En conséquence, GUAPO Web Designer décline toute responsabilité pour toute imprécision, inexactitude ou omission portant sur des informations disponibles sur ce site.",
    "legal.law.title": "Droit applicable",
    "legal.law.content": "Les présentes mentions légales sont soumises au droit français. Tout litige relatif à l'utilisation du site guapowebdesigner.com sera de la compétence exclusive des tribunaux français.",
    "legal.contact.title": "Contact",
    "legal.contact.content": "Pour toute question concernant ces mentions légales :",
    "legal.back": "Retour à l'accueil",
    
    // Privacy Policy
    "privacy.meta.title": "Politique de confidentialité - GUAPO Web Designer",
    "privacy.meta.description": "Politique de confidentialité et protection des données personnelles conforme au RGPD",
    "privacy.badge": "Conforme RGPD",
    "privacy.title": "Politique de",
    "privacy.title.highlight": "Confidentialité",
    "privacy.subtitle": "Dernière mise à jour : 10 novembre 2025",
    "privacy.intro.title": "Introduction",
    "privacy.intro.content1": "GUAPO Web Designer, accessible à l'adresse guapowebdesigner.com, s'engage à protéger la vie privée de ses utilisateurs et à respecter le Règlement Général sur la Protection des Données (RGPD).",
    "privacy.intro.content2": "Cette politique de confidentialité explique quelles données nous collectons, pourquoi nous les collectons, et comment nous les utilisons.",
    "privacy.controller.title": "Responsable du traitement",
    "privacy.controller.name": "Nom :",
    "privacy.controller.email": "Email :",
    "privacy.controller.website": "Site web :",
    "privacy.data.title": "Données collectées",
    "privacy.data.form.title": "Formulaire de contact et devis",
    "privacy.data.form.name": "Nom et prénom",
    "privacy.data.form.email": "Adresse email",
    "privacy.data.form.phone": "Numéro de téléphone (optionnel)",
    "privacy.data.form.company": "Nom de l'entreprise (optionnel)",
    "privacy.data.form.details": "Détails du projet",
    "privacy.data.cookies.title": "Cookies",
    "privacy.data.cookies.essential": "Cookies essentiels : Nécessaires au fonctionnement du site",
    "privacy.data.cookies.analytics": "Cookies analytiques : Pour améliorer l'expérience utilisateur (avec votre consentement)",
    "privacy.usage.title": "Utilisation des données",
    "privacy.usage.intro": "Nous utilisons vos données personnelles uniquement pour :",
    "privacy.usage.contact": "Répondre à vos demandes de contact et de devis",
    "privacy.usage.services": "Vous fournir les services demandés",
    "privacy.usage.improve": "Améliorer notre site et nos services",
    "privacy.usage.legal": "Respecter nos obligations légales",
    "privacy.usage.no_sell": "Nous ne vendons jamais vos données à des tiers.",
    "privacy.retention.title": "Conservation des données",
    "privacy.retention.intro": "Vos données personnelles sont conservées uniquement le temps nécessaire aux finalités pour lesquelles elles ont été collectées :",
    "privacy.retention.contact": "Demandes de contact : 3 ans maximum",
    "privacy.retention.cookies": "Cookies : 13 mois maximum",
    "privacy.rights.title": "Vos droits RGPD",
    "privacy.rights.intro": "Conformément au RGPD, vous disposez des droits suivants :",
    "privacy.rights.access": "Droit d'accès : Obtenir une copie de vos données personnelles",
    "privacy.rights.rectification": "Droit de rectification : Corriger vos données inexactes",
    "privacy.rights.erasure": "Droit à l'effacement : Supprimer vos données personnelles",
    "privacy.rights.objection": "Droit d'opposition : Vous opposer au traitement de vos données",
    "privacy.rights.portability": "Droit à la portabilité : Récupérer vos données dans un format structuré",
    "privacy.rights.contact": "Pour exercer ces droits, contactez-nous à :",
    "privacy.security.title": "Sécurité des données",
    "privacy.security.intro": "Nous mettons en œuvre des mesures de sécurité techniques et organisationnelles appropriées pour protéger vos données personnelles contre :",
    "privacy.security.loss": "La perte ou la destruction accidentelle",
    "privacy.security.access": "L'accès non autorisé",
    "privacy.security.disclosure": "La divulgation ou l'altération",
    "privacy.security.ssl": "🔒 Connexion SSL : Toutes les communications sont chiffrées via HTTPS.",
    "privacy.contact.title": "Contact",
    "privacy.contact.content": "Pour toute question concernant cette politique de confidentialité ou l'exercice de vos droits :",
    "privacy.back": "Retour à l'accueil",
    
    "footer.description": "Nous créons des designs colorés et joyeux qui donnent vie à vos projets digitaux.",
    "footer.links": "Liens rapides",
    "footer.legal": "Informations légales",
    "footer.privacy": "Politique de confidentialité",
    "footer.legal.terms": "Mentions légales",
    "footer.social": "Suivez-nous",
    "footer.copyright": "Guapo Web Designer 2025",
    "footer.rights": "Tous droits réservés."
  },
    nl: {
      // Navigation
      "nav.home": "Home",
      "nav.about": "Over ons",
      "nav.services": "Diensten",
      "nav.portfolio": "Portfolio",
      "nav.contact": "Contact",
      "nav.quote": "Gratis offerte",
      
      // Hero
      "hero.badge": "Guapo Web Designer",
    "hero.title": "Als je het kunt bedenken, kunnen wij het",
    "hero.title.highlight": "ontwerpen.",
    "hero.subtitle": "Websites ontworpen om uw zichtbaarheid te verbeteren en uw bedrijf te professionaliseren",
    "hero.cta.projects": "Bekijk onze projecten",
    "hero.cta.contact": "Neem contact op",
    
      // Announcement Banner
      "announcement.offer": "",
      "announcement.subtitle": "",
      
      // About
    "about.title": "Over Guapo",
    "about.values.passion": "Passie",
    "about.values.passion.desc": "Elk project is uniek en verdient bijzondere aandacht",
    "about.values.innovation": "Innovatie",
    "about.values.innovation.desc": "Altijd voorop in de trends",
    "about.values.performance": "Prestatie",
    "about.values.performance.desc": "Snelle en geoptimaliseerde websites",
    "about.values.creativity": "Creativiteit",
    "about.values.creativity.desc": "Unieke en gedenkwaardige ontwerpen",
    "about.heading": "Gepassioneerde maker",
    "about.intro": "Gepassioneerd door design en nieuwe technologieën, creëren wij moderne, elegante en krachtige websites. Onze aanpak combineert creativiteit, technische expertise en aandacht voor detail om uw digitale projecten tot leven te brengen.",
    "about.p1": "Elk project is uniek en verdient bijzondere aandacht.",
    "about.badge.design": "🎨 UI/UX Design",
    "about.badge.performance": "⚡ Optimale prestaties",
    "about.badge.tech": "🚀 Moderne technologieën",
    
    // Services - Website Cards Section
    "services.website.title.prefix": "Heeft u een",
    "services.website.title.highlight": "Website",
    "services.website.subtitle": "Kies de oplossing die bij uw behoeften past",
    "services.website.showcase.title": "Showcase Website",
    "services.website.showcase.desc": "Professionele website om uw bedrijf, diensten en expertise te presenteren. Ideaal voor restaurants, kantoren, KMO's en portfolio's.",
    "services.website.ecommerce.title": "E-commerce Website",
    "services.website.ecommerce.desc": "Verkoop uw producten online met een professionele en veilige winkel. Orderbeheer, online betalingen, voorraadbeheer.",
    "services.website.discuss.title": "Laten we Samen Praten",
    "services.website.discuss.desc": "Heeft u een op maat gemaakt project of specifieke behoeften? Neem contact met ons op om erover te praten en samen de beste oplossing te vinden.",
    "services.website.discuss.cta": "Neem contact op",
    "services.website.cta": "Vraag een offerte aan",
    
    // Services Page
    "services.page.title": "Onze Diensten",
    "services.desktop.title": "Desktop Showcase Sites",
    "services.desktop.desc": "Websites geoptimaliseerd for grote schermen met professionele en moderne ontwerpen",
    "services.tablet.title": "Tablet Aanpassing",
    "services.tablet.desc": "Interfaces perfect aangepast aan tablets for een vloeiende ervaring",
    "services.mobile.title": "Mobiele Optimalisatie",
    "services.mobile.desc": "Optimale navigatie op smartphones met maximale prestaties",
    "services.responsive.title": "Responsive Design",
    "services.responsive.desc": "Automatische aanpassing aan alle soorten apparaten en resoluties",
    "services.branding.title": "Visuele Identiteit",
    "services.branding.desc": "Creatie van logo's, grafische handvesten en unieke visuele elementen",
    "services.performance.title": "Web Prestaties",
    "services.performance.desc": "Ultrasnelle websites geoptimaliseerd voor SEO en gebruikerservaring",
    "services.cta.title": "Heeft u een showcase site nodig? 🚀",
    "services.cta.desc": "Restaurant, professioneel kantoor, bedrijf of persoonlijke portfolio: wij creëren uw showcase site toegankelijk op alle apparaten!",
    "services.cta.button": "Laten we praten over uw project 💬",
    
    // Services
    "services.title": "Onze",
    "services.title.highlight": "Diensten",
    "services.subtitle": "Wat wij voor u kunnen doen",
    "services.design.title": "UI/UX Design",
    "services.design.desc": "Creatie van intuïtieve en aantrekkelijke gebruikersinterfaces met een optimale ervaring.",
    "services.dev.title": "Web Ontwikkeling",
    "services.dev.desc": "Ontwikkeling van moderne websites met React, Next.js en de nieuwste technologieën.",
    
    // Portfolio
    "portfolio.title.prefix": "Port",
    "portfolio.title.highlight": "folio",
    "portfolio.subtitle": "Onze recente projecten",
    
    // Contact Section
    "contact.section.title": "Neem contact op",
    "contact.section.subtitle": "Laten we uw ideeën omzetten in digitale realiteit",
    "contact.section.desc": "Heeft u een project in gedachten? Neem gerust contact met ons op om erover te praten. We helpen u graag bij het creëren van uw website.",
    "contact.quote.title": "Gratis Offerte",
    "contact.quote.desc": "Krijg een schatting",
    
    // Contact Page
    "contact.page.title": "Neem contact op",
    "contact.page.intro": "Heeft u een moderne en krachtige website nodig? Neem nu contact met ons op!",
    "contact.email.title": "Email",
    "contact.email.address": "info@guapowebdesigner.com",
    "contact.email.copy": "Kopiëren",
    "contact.email.copied": "Email gekopieerd!",
    "contact.instagram.title": "Instagram",
    "contact.instagram.handle": "@guapo.webdesigner",
    "contact.instagram.copy": "Kopiëren",
    "contact.instagram.copied": "Handle gekopieerd!",
    "contact.form.title": "Offerte aanvraag",
    "contact.form.name": "Volledige naam",
    "contact.form.email": "Email",
    "contact.form.phone": "Telefoon (optioneel)",
    "contact.form.message": "Bericht",
    "contact.form.submit": "Verstuur aanvraag",
    "contact.form.sending": "Bezig met versturen...",
    "contact.form.success": "Aanvraag succesvol verzonden!",
    "contact.form.error": "Fout bij verzenden. Probeer het opnieuw.",
    
    // Quote Page
    "quote.page.badge": "Gratis offerte binnen 48 uur",
    "quote.page.title": "Offerte",
    "quote.page.title.highlight": "Aanvraag",
    "quote.page.subtitle": "Vertel ons over uw project en ontvang een gepersonaliseerde offerte die is afgestemd op uw behoeften en budget.",
    "quote.page.card1.title": "Snel antwoord",
    "quote.page.card1.desc": "Offerte binnen 48 uur",
    "quote.page.card2.title": "Gratis offerte",
    "quote.page.card2.desc": "Zonder verplichting",
    "quote.page.card3.title": "Op maat",
    "quote.page.card3.desc": "Aangepast aan uw behoeften",
    "quote.page.cta.title": "Heeft u vragen voordat u uw aanvraag indient?",
    "quote.page.cta.desc": "Neem gerust rechtstreeks contact met ons op via e-mail of Instagram",
    
    // Quote Form - Step 1: Type Selection
    "quote.type.title": "Welk type project wilt u?",
    "quote.type.subtitle": "Kies het type site dat bij uw behoeften past",
    "quote.type.showcase": "Showcase Site",
    "quote.type.showcase.desc": "Presentatiewebsite for uw bedrijf, portfolio of professionele activiteit",
    "quote.type.showcase.feature1": "Bedrijfspresentatie",
    "quote.type.showcase.feature2": "Professionele portfolio",
    "quote.type.showcase.feature3": "Contactformulieren",
    "quote.type.showcase.feature4": "Op maat gemaakt ontwerp",
    "quote.type.ecommerce": "E-commerce Site",
    "quote.type.ecommerce.desc": "Complete online winkel om uw producten of diensten online te verkopen",
    "quote.type.ecommerce.feature1": "Productcatalogus",
    "quote.type.ecommerce.feature2": "Winkelwagen & online betaling",
    "quote.type.ecommerce.feature3": "Bestellingsbeheer",
    "quote.type.ecommerce.feature4": "Klantaccounts",
    "quote.type.menu": "Menu / Bestelsite",
    "quote.type.menu.desc": "Bestelsite voor restaurant met digitaal menu, QR-code en realtime orderbeheer",
    "quote.type.menu.feature1": "Basissysteem",
    "quote.type.menu.feature2": "Categorieën en gerechten",
    "quote.type.menu.feature3": "Mobiel geoptimaliseerd",
    "quote.type.menu.feature4": "Restaurant design",
    "quote.menu.base.title": "Basissysteem",
    "quote.menu.base.name": "Basissysteem",
    "quote.menu.base.desc": "klikbaar menu, categorieën en gerechten, responsive mobile en geoptimaliseerd restaurant design",
    "quote.menu.restaurantFeatures": "Restaurant Functionaliteiten",
      "quote.menu.resto.kitchen": "Keuken Dashboard",
      "quote.menu.resto.kitchen.desc": "Speciale interface voor de keuken: real-time orderontvangst et beheer",
      "quote.menu.resto.status": "Bestelstatus",
      "quote.menu.resto.status.desc": "Gerechten markeren als 'in bereiding', 'klaar' of 'geserveerd'",
      "quote.menu.resto.stock": "Voorraadbeheer",
      "quote.menu.resto.stock.desc": "Schakel gerechten uit met één klik als ze op zijn",
      "quote.menu.resto.waiter": "Ober Dashboard",
      "quote.menu.resto.waiter.desc": "Interface voor kelners: order-opvolging et klantoproepen",
      "quote.menu.resto.waiterStatus": "Ober Bestelstatus",
      "quote.menu.resto.waiterStatus.desc": "Opvolging van de levenscyclus van bestellingen per tafel",
      "quote.menu.resto.menuManagement": "Menu beheer",
      "quote.menu.resto.menuManagement.desc": "Beheersinterface om zelf gerechten et prijzen aan te passen",
        "quote.menu.subscription.title": "Kies uw menubeheerpakket",
          "quote.menu.subscription.simple.name": "Eenvoudig Menupakket",
          "quote.menu.subscription.simple.desc": "Gerechten toevoegen, verwijderen en wijzigen met gemak",
          "quote.menu.subscription.complete.name": "Volledig Menupakket",
              "quote.menu.subscription.complete.desc": "Eenvoudig pakket + creatie van meerdere menu's (Seizoen, Feesten, enz.)",
              "quote.menu.subscription.freeMonth": "",
              "quote.menu.clientFeatures": "Klant Functionaliteiten",
          "quote.menu.client.cart": "Toevoegen aan winkelwagen",
          "quote.menu.client.cart.desc": "Klanten toestaan hun gerechten te selecteren",
          "quote.menu.client.dineIn": "Ter plaatse / Afhalen",
          "quote.menu.client.dineIn.desc": "Keuze van consumptiewijze",
          "quote.menu.client.confirmation": "Bestelbevestiging",
          "quote.menu.client.confirmation.desc": "Eindoverzicht for validatie",
          "quote.menu.client.email": "Automatische klantmail",
          "quote.menu.client.email.desc": "Automatisch ontvangstbewijs per e-mail naar de klant",

      "quote.type.start": "Beginnen",
      
      // Quote Form - Step 2: Questions
      "quote.back": "Terug naar projecttype keuze",
      "quote.selected": "Geselecteerd projecttype:",
      "quote.showcase.pages": "Aantal pagina's van de showcase site",
      "quote.ecommerce.size": "Grootte van uw e-commerce winkel",
      "quote.ecommerce.small": "Kleine winkel (1-20 producten)",
      "quote.ecommerce.small.desc": "Ideaal om te starten met een beperkte selectie",
      "quote.ecommerce.medium": "Middelgrote winkel (21-100 producten)",
      "quote.ecommerce.medium.desc": "Voor een gediversifieerd productassortiment",
      "quote.ecommerce.large": "Grote winkel (100+ produits)",
      "quote.ecommerce.large.desc": "Complete catalogus met geavanceerd beheer",
      "quote.ecommerce.note": "Onze prijzen zijn op aanvraag en afgestemd op uw project",
    "quote.selected.label": "Geselecteerd type:",
    "quote.selected.size": "Geselecteerde grootte:",
    "quote.modify": "Wijzigen",
    "quote.features.ecommerce": "E-commerce Functionaliteiten",
    "quote.optimization.pack": "Alles Inclusief Pakket",
    "quote.optimization.pack.desc": "Inclusief alle essentiële optimalisaties voor een professionele en krachtige website",
    "quote.optimization.pack.seo": "Basis SEO",
    "quote.optimization.pack.performance": "Snelheidsoptimalisatie",
    "quote.optimization.pack.ssl": "SSL-certificaat/HTTPS",
    "quote.optimization.pack.gdpr": "AVG-naleving",
    "quote.optimization.recommended": "⭐ AANBEVOLEN",
    "quote.optimization.or": "of kies individueel",
    "quote.hosting.auto": "Hosting is automatisch inbegrepen in uw project.",
    
    // Quote Form
    "quote.success.title": "Bedankt for uw aanvraag!",
    "quote.info.title": "Informatie",
    "quote.info.firstName": "Voornaam",
    "quote.info.firstNamePlaceholder": "Uw voornaam",
    "quote.info.lastName": "Achternaam",
    "quote.info.lastNamePlaceholder": "Uw achternaam",
    "quote.info.email": "Email",
    "quote.info.emailPlaceholder": "uw@email.com",
    "quote.info.company": "Bedrijfsnaam / Project",
    "quote.info.companyPlaceholder": "Naam van uw bedrijf of project",
    "quote.info.sector": "Sector (optioneel)",
    "quote.info.sectorPlaceholder": "Bv: Horeca, Diensten, etc.",
    "quote.siteType.title": "Type Website",
    "quote.siteType.simple": "Eenvoudige showcase site (1 tot 3 pagina's)",
    "quote.siteType.simpleDesc": "Ideaal om uw activity te presenteren met de essentiële pagina's",
    "quote.siteType.standard": "Standaard showcase site (4 tot 5 pagina's)",
    "quote.siteType.standardDesc": "Voor een complete webpresentie met meer inhoud",
    "quote.siteType.advanced": "Geavanceerde showcase site (6 tot 8 pagina's)",
    "quote.siteType.advancedDesc": "Voor een gedetailleerde presentatie van uw bedrijf",
    "quote.siteType.premium": "Premium showcase site (9 tot 12 pagina's)",
    "quote.siteType.premiumDesc": "Voor een complete site met alle nodige informatie",
    "quote.siteType.portfolio": "Portfolio / persoonlijke site",
    "quote.siteType.portfolioDesc": "Laat uw prestaties en expertise zien",
    "quote.siteType.ecommerce": "E-commerce site",
    "quote.siteType.ecommerceDesc": "Complete online winkel met product- en betalingsbeheer",
    "quote.design.title": "Design & Inhoud",
    "quote.design.custom": "Op maat gemaakt design (gepersonaliseerde UX/UI) - Inbegrepen",
    "quote.design.responsive": "Responsive (mobiel + tablet + computer) - Inbegrepen",
    "quote.design.pageCount": "Verwacht aantal pagina's",
    "quote.design.pageCountPlaceholder": "Bv: 5",
    "quote.features.title": "Functionaliteiten / Modules",
    "quote.features.contactForm": "Eenvoudig contactformulier",
    "quote.features.quoteForm": "Offerteaanvraagformulier",
    "quote.features.autoEmailsQuote": "Automatisch verzenden van bevestigingsmails (voor offerte)",
    "quote.features.booking": "Online afspraaksysteem (met automatische e-mails)",
    "quote.features.calendar": "Toevoegen aan agenda (Google Agenda, Outlook, ICS, etc.)",
    "quote.features.multilingual": "Meertalig",
    "quote.features.selectLanguages": "Selecteer de gewenste talen:",
    "quote.features.otherLanguage": "Andere taal",
    "quote.features.otherLanguagePlaceholder": "Bv: Spaans, Italiaans, Duits...",
    "quote.features.productCatalog": "Productcatalogus",
    "quote.features.shoppingCart": "Winkelwagen",
    "quote.features.paymentGateway": "Betaalgateway (Stripe, PayPal, etc.)",
    "quote.features.orderManagement": "Bestellingsbeheer",
    "quote.features.inventoryManagement": "Voorraadbeheer",
    "quote.features.customerAccounts": "Klantaccounts",
    "quote.optimization.title": "Optimalisatie & Beveiliging",
    "quote.optimization.seo": "Basis SEO (tags, titels, URLs)",
    "quote.optimization.performance": "Snelheids- / prestatieoptimalisatie",
    "quote.optimization.ssl": "SSL-certificaat / HTTPS",
    "quote.optimization.gdpr": "AVG / wettelijke naleving",
    "quote.hosting.title": "Hosting",
    "quote.hosting.hosting": "Hosting",
    "quote.hosting.domain": "Domeinnaam",
    "quote.hosting.selectOption": "Selecteer een optie",
    "quote.hosting.included": "Inbegrepen in het project",
    "quote.hosting.clientProvided": "Verstrekt door de klant",
    "quote.hosting.toDiscuss": "Te bespreken",
    "quote.message.title": "Specifieke opmerkingen / Bijzondere behoeften",
    "quote.message.label": "Gedetailleerde beschrijving van uw project",
    "quote.message.placeholder": "Beschrijf uw project in detail: uw doelstellingen, uw doelgroep, uw specifieke behoeften, voorbeelden van sites die u leuk vindt, bijzondere beperkingen, etc.",
    "quote.gdpr.title": "AVG-toestemming",
    "quote.gdpr.text": "Ik ga ermee akkoord dat mijn persoonlijke gegevens worden verzameld en verwerkt door GUAPO Web Designer om mijn offerteaanvraag te verwerken. Mijn gegevens worden nooit aan derden verkocht. Ik kan mijn rechten uitoefenen (toegang, rectificatie, verwijdering) door contact op te nemen met",
    "quote.gdpr.moreInfo": "Voor meer informatie, raadpleeg ons",
    "quote.gdpr.privacyPolicy": "privacybeleid",
    "quote.submit.button": "Mijn offerteaanvraag verzenden",
    "quote.submit.sending": "Bezig met verzenden...",
    "quote.submit.required": "* Verplichte velden",
    
    // Footer
    "footer.description": "Maker van moderne en krachtige websites. Uw visie, our expertise.",
    "footer.links": "Snelle links",
    "footer.legal": "Juridische informatie",
    "footer.privacy": "Privacybeleid",
    "footer.legal.terms": "Algemene voorwaarden",
    "footer.social": "Volg ons",
    "footer.copyright": "Guapo Web Designer 2025",
    "footer.rights": "Alle rechten voorbehouden."
  },
    en: {
      // Navigation
      "nav.home": "Home",
      "nav.about": "About",
      "nav.services": "Services",
      "nav.portfolio": "Portfolio",
      "nav.contact": "Contact",
      "nav.quote": "Free Quote",
      
      // Hero
      "hero.badge": "Guapo Web Designer",
    "hero.title": "If you can imagine it, we can",
    "hero.title.highlight": "design it.",
    "hero.subtitle": "Websites designed to improve your visibility and professionalize your business",
    "hero.cta.projects": "View our projects",
    "hero.cta.contact": "Contact us",
    
      // Announcement Banner
      "announcement.offer": "",
      "announcement.subtitle": "",
      
      // About
    "about.title": "About Guapo",
    "about.values.passion": "Passion",
    "about.values.passion.desc": "Every project is a new creative adventure",
    "about.values.innovation": "Innovation",
    "about.values.innovation.desc": "At the forefront of trends",
    "about.values.performance": "Performance",
    "about.values.performance.desc": "Fast and optimized websites",
    "about.values.creativity": "Creativity",
    "about.values.creativity.desc": "Unique and memorable designs",
    "about.heading": "Passionate creator",
    "about.intro": "Passionate about design and new technologies, we create modern, elegant and powerful websites. Our approach combines creativity, technical expertise and attention to detail to bring your digital projects to life.",
    "about.p1": "Each project is unique and deserves special attention.",
    "about.badge.design": "🎨 UI/UX Design",
    "about.badge.performance": "⚡ Optimal performance",
    "about.badge.tech": "🚀 Modern technologies",
    
    // Services - Website Cards Section
    "services.website.title.prefix": "Need a",
    "services.website.title.highlight": "Website",
    "services.website.subtitle": "Choose the solution that fits your needs",
    "services.website.showcase.title": "Showcase Website",
    "services.website.showcase.desc": "Professional website to present your company, services and expertise. Ideal for restaurants, offices, SMEs and portfolios.",
    "services.website.ecommerce.title": "E-commerce Website",
    "services.website.ecommerce.desc": "Sell your products online with a professional and secure store. Order management, online payments, stock tracking.",
    "services.website.discuss.title": "Let's Talk Together",
    "services.website.discuss.desc": "Do you have a custom project or specific needs? Contact us to discuss it and find the best solution together.",
    "services.website.discuss.cta": "Contact us",
    "services.website.cta": "Get a quote",
    
    // Services Page
    "services.page.title": "Our Services",
    "services.desktop.title": "Desktop Showcase Sites",
    "services.desktop.desc": "Websites optimized for large screens with professional and modern designs",
    "services.tablet.title": "Tablet Adaptation",
    "services.tablet.desc": "Interfaces perfectly adapted to tablets for a smooth experience",
    "services.mobile.title": "Mobile Optimization",
    "services.mobile.desc": "Optimal navigation on smartphones with maximum performance",
    "services.responsive.title": "Responsive Design",
    "services.responsive.desc": "Automatic adaptation to all types of devices and resolutions",
    "services.branding.title": "Visual Identity",
    "services.branding.desc": "Creation of logos, graphic guidelines and unique visual elements",
    "services.performance.title": "Web Performance",
    "services.performance.desc": "Ultra-fast websites optimized for SEO and user experience",
    "services.cta.title": "Need a showcase website? 🚀",
    "services.cta.desc": "Restaurant, professional office, company or personal portfolio: we create your showcase website accessible on all devices!",
    "services.cta.button": "Let's discuss your project 💬",
    
    // Services
    "services.title": "Our",
    "services.title.highlight": "Services",
    "services.subtitle": "What we can do for you",
    "services.design.title": "UI/UX Design",
    "services.design.desc": "Creation of intuitive and attractive user interfaces with an optimal experience.",
    "services.dev.title": "Web Development",
    "services.dev.desc": "Development of modern websites with React, Next.js and the latest technologies.",
    
    // Portfolio
    "portfolio.title.prefix": "Port",
    "portfolio.title.highlight": "folio",
    "portfolio.subtitle": "Our recent projects",
    
    // Contact Section
    "contact.section.title": "Contact us",
    "contact.section.subtitle": "Let's turn your ideas into digital reality",
    "contact.section.desc": "Got a project in mind? Don't hesitate to contact us to discuss it. We'll be happy to help you create your website.",
    "contact.quote.title": "Free Quote",
    "contact.quote.desc": "Get an estimate",
    
    // Contact Page
    "contact.page.title": "Contact Us",
    "contact.page.intro": "Need a modern and powerful website? Contact us now!",
    "contact.email.title": "Email",
    "contact.email.address": "info@guapowebdesigner.com",
    "contact.email.copy": "Copy",
    "contact.email.copied": "Email copied!",
    "contact.instagram.title": "Instagram",
    "contact.instagram.handle": "@guapo.webdesigner",
    "contact.instagram.copy": "Copy",
    "contact.instagram.copied": "Handle copied!",
    "contact.form.title": "Quote Request",
    "contact.form.name": "Full Name",
    "contact.form.email": "Email",
    "contact.form.phone": "Phone (optional)",
    "contact.form.message": "Message",
    "contact.form.submit": "Send Request",
    "contact.form.sending": "Sending...",
    "contact.form.success": "Request sent successfully!",
    "contact.form.error": "Error sending. Please try again.",
    
    // Quote Page
    "quote.page.badge": "Free quote within 48 hours",
    "quote.page.title": "Quote",
    "quote.page.title.highlight": "Request",
    "quote.page.subtitle": "Tell us about your project and receive a personalized quote tailored to your needs and budget.",
    "quote.page.card1.title": "Fast response",
    "quote.page.card1.desc": "Quote within 48 hours",
    "quote.page.card2.title": "Free quote",
    "quote.page.card2.desc": "No commitment",
    "quote.page.card3.title": "Custom-made",
    "quote.page.card3.desc": "Tailored to your needs",
    "quote.page.cta.title": "Questions before submitting your request?",
    "quote.page.cta.desc": "Feel free to contact us directly by email or Instagram",
    
    // Quote Form - Step 1: Type Selection
    "quote.type.title": "What type of project do you want?",
    "quote.type.subtitle": "Choose the type of site that suits your needs",
    "quote.type.showcase": "Showcase Website",
    "quote.type.showcase.desc": "Presentation website for your business, portfolio, or professional activity",
    "quote.type.showcase.feature1": "Business presentation",
    "quote.type.showcase.feature2": "Professional portfolio",
    "quote.type.showcase.feature3": "Contact forms",
    "quote.type.showcase.feature4": "Custom design",
    "quote.type.ecommerce": "E-commerce Website",
    "quote.type.ecommerce.desc": "Complete online store to sell your products or services online",
    "quote.type.ecommerce.feature1": "Product catalog",
    "quote.type.ecommerce.feature2": "Shopping cart & online payment",
    "quote.type.ecommerce.feature3": "Order management",
    "quote.type.ecommerce.feature4": "Customer accounts",
    "quote.type.menu": "Menu / Ordering Site",
    "quote.type.menu.desc": "Restaurant ordering site with digital menu, QR code and real-time order management",
    "quote.type.menu.feature1": "Base system",
    "quote.type.menu.feature2": "Categories and dishes",
    "quote.type.menu.feature3": "Mobile optimized",
    "quote.type.menu.feature4": "Restaurant design",
    "quote.menu.base.title": "Base System",
    "quote.menu.base.name": "Base system",
    "quote.menu.base.desc": "clickable menu, categories and dishes, mobile responsive and optimized restaurant design",
    "quote.menu.restaurantFeatures": "Restaurant Features",
        "quote.menu.resto.kitchen": "Kitchen Dashboard",
          "quote.menu.resto.kitchen.desc": "Dedicated interface for the kitchen: real-time order reception and management",
          "quote.menu.resto.status": "Order status",
          "quote.menu.resto.status.desc": "Mark dishes as 'in preparation', 'ready' or 'served'",
          "quote.menu.resto.stock": "Stock management",
          "quote.menu.resto.stock.desc": "Disable dishes from the menu with one click if they are out of stock",
          "quote.menu.resto.waiter": "Waiter Dashboard",
          "quote.menu.resto.waiter.desc": "Interface for waiters: order tracking and customer calls",
          "quote.menu.resto.waiterStatus": "Waiter Order status",
          "quote.menu.resto.waiterStatus.desc": "Tracking order lifecycle by table",
          "quote.menu.resto.menuManagement": "Menu management",
          "quote.menu.resto.menuManagement.desc": "Admin interface to modify your dishes and prices independently",
        "quote.menu.subscription.title": "Choose your menu management pack",
          "quote.menu.subscription.simple.name": "Simple Menu Pack",
          "quote.menu.subscription.simple.desc": "Add, delete and modify your dishes with ease",
          "quote.menu.subscription.complete.name": "Complete Menu Pack",
            "quote.menu.subscription.complete.desc": "Simple Pack + creation of multiple menus (Season, Holidays, etc.)",
            "quote.menu.subscription.freeMonth": "",
            "quote.menu.clientFeatures": "Client Features",
          "quote.menu.client.cart": "Add to cart",
          "quote.menu.client.cart.desc": "Allow customers to select their dishes",
          "quote.menu.client.dineIn": "Dine-in / Take-away",
          "quote.menu.client.dineIn.desc": "Choice of consumption mode",
          "quote.menu.client.confirmation": "Order Confirmation",
          "quote.menu.client.confirmation.desc": "Final summary before validation",
          "quote.menu.client.email": "Automatic Client Email",
          "quote.menu.client.email.desc": "Sending an automatic receipt by email to the customer",

      "quote.type.start": "Start",
      
      // Quote Form - Step 2: Questions
      "quote.back": "Back to project type selection",
      "quote.selected": "Selected project type:",
      "quote.showcase.pages": "Number of pages for the showcase website",
      "quote.ecommerce.size": "Size of your e-commerce store",
      "quote.ecommerce.small": "Small store (1-20 products)",
      "quote.ecommerce.small.desc": "Ideal to start with a limited selection",
      "quote.ecommerce.medium": "Medium store (21-100 products)",
      "quote.ecommerce.medium.desc": "For a diversified product range",
      "quote.ecommerce.large": "Large store (100+ products)",
      "quote.ecommerce.large.desc": "Complete catalog with advanced management",
      "quote.ecommerce.note": "Our prices are on request and tailored to your project",
    "quote.selected.label": "Selected type:",
    "quote.selected.size": "Selected size:",
    "quote.modify": "Edit",
    "quote.features.ecommerce": "E-commerce Features",
    "quote.optimization.pack": "All-Inclusive Package",
    "quote.optimization.pack.desc": "Includes all essential optimizations for a professional and powerful website",
    "quote.optimization.pack.seo": "Basic SEO",
    "quote.optimization.pack.performance": "Speed optimization",
    "quote.optimization.pack.ssl": "SSL certificate/HTTPS",
    "quote.optimization.pack.gdpr": "GDPR compliance",
    "quote.optimization.recommended": "⭐ RECOMMENDED",
    "quote.optimization.or": "or choose individually",
    "quote.hosting.auto": "Hosting is automatically included in your project.",
    
    // Quote Form
    "quote.success.title": "Thank you for your request!",
    "quote.info.title": "Information",
    "quote.info.firstName": "First Name",
    "quote.info.firstNamePlaceholder": "Your first name",
    "quote.info.lastName": "Last Name",
    "quote.info.lastNamePlaceholder": "Your last name",
    "quote.info.email": "Email",
    "quote.info.emailPlaceholder": "your@email.com",
    "quote.info.company": "Company / Project Name",
    "quote.info.companyPlaceholder": "Name of your company or project",
    "quote.info.sector": "Business Sector (optional)",
    "quote.info.sectorPlaceholder": "E.g.: Restaurant, Services, etc.",
    "quote.siteType.title": "Website Type",
    "quote.siteType.simple": "Simple showcase site (1 to 3 pages)",
    "quote.siteType.simpleDesc": "Ideal for presenting your activity with essential pages",
    "quote.siteType.standard": "Standard showcase site (4 to 5 pages)",
    "quote.siteType.standardDesc": "For a complete web presence with more content",
    "quote.siteType.advanced": "Advanced showcase site (6 to 8 pages)",
    "quote.siteType.advancedDesc": "For a detailed presentation of your company",
    "quote.siteType.premium": "Premium showcase site (9 to 12 pages)",
    "quote.siteType.premiumDesc": "For a complete website with all necessary information",
    "quote.siteType.portfolio": "Portfolio / personal site",
    "quote.siteType.portfolioDesc": "Showcase your achievements and expertise",
    "quote.siteType.ecommerce": "E-commerce site",
    "quote.siteType.ecommerceDesc": "Complete online store with product and payment management",
    "quote.design.title": "Design & Content",
    "quote.design.custom": "Custom design (personalized UX/UI) - Included",
    "quote.design.responsive": "Responsive (mobile + tablet + desktop) - Included",
    "quote.design.pageCount": "Expected number of pages",
    "quote.design.pageCountPlaceholder": "E.g.: 5",
    "quote.features.title": "Features / Modules",
    "quote.features.contactForm": "Simple contact form",
    "quote.features.quoteForm": "Quote request form",
    "quote.features.autoEmailsQuote": "Automatic confirmation emails (for quotes)",
    "quote.features.booking": "Online booking system (with automatic emails)",
    "quote.features.calendar": "Add to calendar (Google Calendar, Outlook, ICS, etc.)",
    "quote.features.multilingual": "Multilingual",
    "quote.features.selectLanguages": "Select desired languages:",
    "quote.features.otherLanguage": "Other language",
    "quote.features.otherLanguagePlaceholder": "E.g: Spanish, Italian, German...",
    "quote.features.productCatalog": "Product catalog",
    "quote.features.shoppingCart": "Shopping cart",
    "quote.features.paymentGateway": "Payment gateway (Stripe, PayPal, etc.)",
    "quote.features.orderManagement": "Order management",
    "quote.features.inventoryManagement": "Inventory management",
    "quote.features.customerAccounts": "Customer accounts",
    "quote.optimization.title": "Optimization & Security",
    "quote.optimization.seo": "Basic SEO (tags, titles, URLs)",
    "quote.optimization.performance": "Speed / performance optimization",
    "quote.optimization.ssl": "SSL certificate / HTTPS",
    "quote.optimization.gdpr": "GDPR / legal compliance",
    "quote.hosting.title": "Hosting",
    "quote.hosting.hosting": "Hosting",
    "quote.hosting.domain": "Domain name",
    "quote.hosting.selectOption": "Select an option",
    "quote.hosting.included": "Included in the project",
    "quote.hosting.clientProvided": "Provided by the client",
    "quote.hosting.toDiscuss": "To discuss",
    "quote.message.title": "Specific Remarks / Special Needs",
    "quote.message.label": "Detailed description of your project",
    "quote.message.placeholder": "Describe your project in detail: your objectives, your target audience, your specific needs, examples of sites you like, particular constraints, etc.",
    "quote.gdpr.title": "GDPR Consent",
    "quote.gdpr.text": "I agree that my personal data will be collected and processed by GUAPO Web Designer for the purpose of processing my quote request. My data will never be sold to third parties. I can exercise my rights (access, rectification, deletion) by contacting",
    "quote.gdpr.moreInfo": "For more information, please consult our",
    "quote.gdpr.privacyPolicy": "privacy policy",
    "quote.submit.button": "Send my quote request",
    "quote.submit.sending": "Sending...",
    "quote.submit.required": "* Required fields",
    
    // Footer
    "footer.description": "Creator of modern and powerful websites. Your vision, our expertise.",
    "footer.links": "Quick Links",
    "footer.legal": "Legal Information",
    "footer.privacy": "Privacy Policy",
    "footer.legal.terms": "Terms and Conditions",
    "footer.social": "Follow Us",
    "footer.copyright": "Guapo Web Designer 2025",
    "footer.rights": "All rights reserved."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const savedLang = localStorage.getItem('language');
    if (savedLang && (savedLang === 'fr' || savedLang === 'nl' || savedLang === 'en')) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.fr] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
