"use client";

import { createContext, useContext, useState, ReactNode } from "react";

type Language = "fr" | "nl" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.about": "À propos",
    "nav.services": "Services",
    "nav.portfolio": "Portfolio",
    "nav.contact": "Contact",
    "nav.quote": "Devis gratuit",
    
    // Promo -30%
    "promo.discount": "-30%",
    "promo.until": "jusqu'au",
    "promo.date": "31/12/25",
    "promo.banner": "-30% jusqu'au 31/12/25 + 1 mois de maintenance offert !",
    "promo.close": "Fermer",
    "promo.badge": "Premier Mois de Maintenance Offert !",
    
    // Hero
    "hero.badge": "Guapo Web Designer",
    "hero.title": "If you can imagine it, we can",
    "hero.title.highlight": "design it.",
    "hero.subtitle": "Des sites web conçus pour améliorer votre visibilité et professionnaliser votre entreprise",
    "hero.cta.projects": "Voir nos projets",
    "hero.cta.contact": "Nous contacter",
    
    // Announcement Banner
    "announcement.offer": "🎁 1 mois de maintenance inclus à la création de chaque site !",
    
    // About
    "about.title": "À propos de Guapo",
    "about.values.passion": "Passion",
    "about.values.passion.desc": "Chaque projet est une nouvelle aventure créative",
    "about.values.innovation": "Innovation",
    "about.values.innovation.desc": "Toujours à l'avant-garde des tendances",
    "about.values.performance": "Performance",
    "about.values.performance.desc": "Des sites rapides et optimisés",
    "about.values.creativity": "Créativité",
    "about.values.creativity.desc": "Des designs uniques et mémorables",
    "about.heading": "Créateur passionné",
    "about.intro": "Passionnés par le design et les nouvelles technologies, nous créons des sites web modernes, élégants et performants. Notre approche combine créativité, expertise technique et attention aux détails pour donner vie à vos projets digitaux.",
    "about.intro.highlight": "",
    "about.intro.text": "",
    "about.p1": "Chaque projet est unique et mérite une attention particulière.",
    "about.p2.prefix": "",
    "about.p2.creativity": "",
    "about.p2.innovation": "",
    "about.p2.excellence": "",
    "about.p2.suffix": "",
    "about.badge.design": "🎨 Design UI/UX",
    "about.badge.performance": "⚡ Performance optimale",
    "about.badge.tech": "🚀 Technologies modernes",
    
    // Services Page
    "services.page.title": "Nos Services",
    "services.desktop.title": "Sites Vitrine Desktop",
    "services.desktop.desc": "Sites web optimisés pour écrans larges avec designs professionnels et modernes",
    "services.tablet.title": "Adaptation Tablette",
    "services.tablet.desc": "Interfaces parfaitement adaptées aux tablettes pour une expérience fluide",
    "services.mobile.title": "Optimisation Mobile",
    "services.mobile.desc": "Navigation optimale sur smartphones avec performances maximales",
    "services.responsive.title": "Design Responsive",
    "services.responsive.desc": "Adaptation automatique à tous types d'appareils et résolutions",
    "services.branding.title": "Identité Visuelle",
    "services.branding.desc": "Création de logos, chartes graphiques et éléments visuels uniques",
    "services.performance.title": "Performance Web",
    "services.performance.desc": "Sites ultra-rapides optimisés pour le référencement et l'expérience utilisateur",
    "services.cta.title": "Besoin d'un site vitrine ? 🚀",
    "services.cta.desc": "Restaurant, cabinet professionnel, entreprise ou portfolio personnel : nous créons votre site vitrine accessible sur tous les appareils !",
    "services.cta.button": "Discutons de votre projet 💬",
    
    // Services
    "services.title": "Nos",
    "services.title.highlight": "Services",
    "services.subtitle": "Ce que nous pouvons faire pour vous",
    "services.design.title": "Design UI/UX",
    "services.design.desc": "Création d'interfaces utilisateur intuitives et attrayantes avec une expérience optimale.",
    "services.dev.title": "Développement Web",
    "services.dev.desc": "Développement de sites web modernes avec React, Next.js et les dernières technologies.",
    
    // Portfolio
    "portfolio.title.prefix": "Port",
    "portfolio.title.highlight": "folio",
    "portfolio.subtitle": "Nos projets récents",
    
    // Contact
    "contact.title": "Travaillons",
    "contact.title.highlight": "Ensemble",
    "contact.subtitle": "Vous avez un projet en tête ? Contactez-nous et discutons de vos besoins.",
    
    // Contact Page
    "contact.page.title": "Contactez-nous",
    "contact.page.intro": "Besoin d'un site web moderne et performant ? Contactez-nous dès maintenant !",
    "contact.email.title": "Email",
    "contact.email.address": "info@guapowebdesigner.com",
    "contact.email.copy": "Copier",
    "contact.email.copied": "Email copié !",
    "contact.instagram.title": "Instagram",
    "contact.instagram.handle": "@guapo.webdesigner",
    "contact.instagram.copy": "Copier",
    "contact.instagram.copied": "Handle copié !",
    "contact.form.title": "Demande de devis",
    "contact.form.name": "Nom complet",
    "contact.form.email": "Email",
    "contact.form.phone": "Téléphone (optionnel)",
    "contact.form.message": "Message",
    "contact.form.submit": "Envoyer la demande",
    "contact.form.sending": "Envoi en cours...",
    "contact.form.success": "Demande envoyée avec succès !",
    "contact.form.error": "Erreur lors de l'envoi. Veuillez réessayer.",
    
    // Quote Page
    "quote.page.badge": "Devis gratuit sous 48h",
    "quote.page.title": "Demande de",
    "quote.page.title.highlight": "Devis",
    "quote.page.subtitle": "Parlez-nous de votre projet et recevez un devis personnalisé adapté à vos besoins et votre budget.",
    "quote.page.card1.title": "Réponse rapide",
    "quote.page.card1.desc": "Devis sous 48h maximum",
    "quote.page.card2.title": "Devis gratuit",
    "quote.page.card2.desc": "Sans engagement",
    "quote.page.card3.title": "Sur mesure",
    "quote.page.card3.desc": "Adapté à vos besoins",
    "quote.page.cta.title": "Des questions avant de faire votre demande ?",
    "quote.page.cta.desc": "N'hésitez pas à nous contacter directement par email ou sur Instagram",
    
    // Quote Form - Step 1: Type Selection
    "quote.type.title": "Quel type de projet souhaitez-vous ?",
    "quote.type.subtitle": "Choisissez le type de site qui correspond à vos besoins",
    "quote.type.showcase": "Site Vitrine",
    "quote.type.showcase.desc": "Site web de présentation pour votre entreprise, portfolio, ou activité professionnelle",
    "quote.type.showcase.feature1": "Présentation d'entreprise",
    "quote.type.showcase.feature2": "Portfolio professionnel",
    "quote.type.showcase.feature3": "Formulaires de contact",
    "quote.type.showcase.feature4": "Design sur-mesure",
    "quote.type.ecommerce": "Site E-commerce",
    "quote.type.ecommerce.desc": "Boutique en ligne complète pour vendre vos produits ou services sur internet",
    "quote.type.ecommerce.feature1": "Catalogue produits",
    "quote.type.ecommerce.feature2": "Panier & paiement en ligne",
    "quote.type.ecommerce.feature3": "Gestion des commandes",
    "quote.type.ecommerce.feature4": "Comptes clients",
    "quote.type.start": "Commencer",
    
    // Quote Form - Step 2: Questions
    "quote.back": "Retour au choix du type de projet",
    "quote.selected": "Type de projet sélectionné :",
    "quote.showcase.pages": "Nombre de pages du site vitrine",
    "quote.ecommerce.size": "Taille de votre boutique e-commerce",
    "quote.ecommerce.small": "Petite boutique (1-20 produits)",
    "quote.ecommerce.small.desc": "Idéal pour démarrer avec une sélection limitée",
    "quote.ecommerce.medium": "Boutique moyenne (21-100 produits)",
    "quote.ecommerce.medium.desc": "Pour une gamme de produits diversifiée",
    "quote.ecommerce.large": "Grande boutique (100+ produits)",
    "quote.ecommerce.large.desc": "Catalogue complet avec gestion avancée",
    "quote.ecommerce.note": "Le prix final dépendra des fonctionnalités e-commerce sélectionnées ci-dessous",
    "quote.selected.label": "Type sélectionné :",
    "quote.selected.size": "Taille sélectionnée :",
    "quote.modify": "Modifier",
    "quote.features.ecommerce": "Fonctionnalités E-commerce",
    "quote.optimization.pack": "Pack Tout Inclus",
    "quote.optimization.pack.desc": "Inclut toutes les optimisations essentielles pour un site professionnel et performant",
    "quote.optimization.pack.seo": "SEO de base",
    "quote.optimization.pack.performance": "Optimisation vitesse",
    "quote.optimization.pack.ssl": "Certificat SSL/HTTPS",
    "quote.optimization.pack.gdpr": "Conformité RGPD",
    "quote.optimization.recommended": "⭐ RECOMMANDÉ",
    "quote.optimization.or": "ou choisissez individuellement",
    "quote.hosting.auto": "L'hébergement est automatiquement inclus dans votre projet.",
    
    // Quote Form
    "quote.success.title": "Merci pour votre demande !",
    "quote.info.title": "Informations",
    "quote.info.firstName": "Prénom",
    "quote.info.firstNamePlaceholder": "Votre prénom",
    "quote.info.lastName": "Nom",
    "quote.info.lastNamePlaceholder": "Votre nom",
    "quote.info.email": "Email",
    "quote.info.emailPlaceholder": "votre@email.com",
    "quote.info.company": "Nom de l'entreprise / Projet",
    "quote.info.companyPlaceholder": "Nom de votre entreprise ou projet",
    "quote.info.sector": "Secteur d'activité (facultatif)",
    "quote.info.sectorPlaceholder": "Ex: Restauration, Services, etc.",
    "quote.siteType.title": "Type de Site",
    "quote.siteType.simple": "Site vitrine simple (1 à 3 pages)",
    "quote.siteType.simpleDesc": "Idéal pour présenter votre activité avec les pages essentielles",
    "quote.siteType.standard": "Site vitrine standard (4 à 5 pages)",
    "quote.siteType.standardDesc": "Pour une présence web complète avec plus de contenu",
    "quote.siteType.advanced": "Site vitrine avancé (6 à 8 pages)",
    "quote.siteType.advancedDesc": "Pour une présentation détaillée de votre entreprise",
    "quote.siteType.premium": "Site vitrine premium (9 à 12 pages)",
    "quote.siteType.premiumDesc": "Pour un site complet avec toutes les informations nécessaires",
    "quote.siteType.portfolio": "Portfolio / site personnel",
    "quote.siteType.portfolioDesc": "Mettez en valeur vos réalisations et votre expertise",
    "quote.siteType.ecommerce": "Site e-commerce",
    "quote.siteType.ecommerceDesc": "Boutique en ligne complète avec gestion des produits et paiements",
    "quote.design.title": "Design & Contenu",
    "quote.design.custom": "Design sur mesure (UX/UI personnalisé) - Inclus",
    "quote.design.responsive": "Responsive (mobile + tablette + ordinateur) - Inclus",
    "quote.design.pageCount": "Nombre de pages prévues",
    "quote.design.pageCountPlaceholder": "Ex: 5",
    "quote.features.title": "Fonctionnalités / Modules",
    "quote.features.contactForm": "Formulaire de contact simple",
    "quote.features.quoteForm": "Formulaire de demande de devis",
    "quote.features.autoEmailsQuote": "Envoi automatique d'emails de confirmation (pour devis)",
    "quote.features.booking": "Système de prise de rendez-vous en ligne (avec emails automatiques)",
    "quote.features.calendar": "Ajouter au calendrier (Google Calendar, Outlook, ICS, etc.)",
    "quote.features.multilingual": "Multilingue",
    "quote.features.selectLanguages": "Sélectionnez les langues souhaitées :",
    "quote.features.otherLanguage": "Autre langue",
    "quote.features.otherLanguagePlaceholder": "Ex: Espagnol, Italien, Allemand...",
    "quote.features.productCatalog": "Catalogue de produits",
    "quote.features.shoppingCart": "Panier d'achat",
    "quote.features.paymentGateway": "Passerelle de paiement (Stripe, PayPal, etc.)",
    "quote.features.orderManagement": "Gestion des commandes",
    "quote.features.inventoryManagement": "Gestion des stocks",
    "quote.features.customerAccounts": "Comptes clients",
    "quote.optimization.title": "Optimisation & Sécurité",
    "quote.optimization.seo": "SEO de base (balises, titres, URLs)",
    "quote.optimization.performance": "Optimisation vitesse / performance",
    "quote.optimization.ssl": "Certificat SSL / HTTPS",
    "quote.optimization.gdpr": "RGPD / conformité légale",
    "quote.hosting.title": "Hébergement",
    "quote.hosting.hosting": "Hébergement",
    "quote.hosting.domain": "Nom de domaine",
    "quote.hosting.selectOption": "Sélectionnez une option",
    "quote.hosting.included": "Inclus dans le projet",
    "quote.hosting.clientProvided": "Fourni par le client",
    "quote.hosting.toDiscuss": "À discuter",
    "quote.message.title": "Remarques spécifiques / Besoins particuliers",
    "quote.message.label": "Description détaillée de votre projet",
    "quote.message.placeholder": "Décrivez votre projet en détail : vos objectifs, votre audience cible, vos besoins spécifiques, exemples de sites que vous aimez, contraintes particulières, etc.",
    "quote.gdpr.title": "Consentement RGPD",
    "quote.gdpr.text": "J'accepte que mes données personnelles soient collectées et traitées par GUAPO Web Designer dans le but de traiter ma demande de devis. Mes données ne seront jamais vendues à des tiers. Je peux exercer mes droits (accès, rectification, suppression) en contactant",
    "quote.gdpr.moreInfo": "Pour plus d'informations, consultez notre",
    "quote.gdpr.privacyPolicy": "politique de confidentialité",
    "quote.submit.button": "Envoyer ma demande de devis",
    "quote.submit.sending": "Envoi en cours...",
    "quote.submit.required": "* Champs obligatoires",
    
    "footer.description": "Nous créons des designs colorés et joyeux qui donnent vie à vos projets digitaux.",
    "footer.links": "Liens rapides",
    "footer.legal": "Informations légales",
    "footer.privacy": "Politique de confidentialité",
    "footer.legal.terms": "Mentions légales",
    "footer.social": "Suivez-nous",
    "footer.copyright": "Guapo Web Designer 2025",
    "footer.rights": "Tous droits réservés."
  },
  nl: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "Over ons",
    "nav.services": "Diensten",
    "nav.portfolio": "Portfolio",
    "nav.contact": "Contact",
    "nav.quote": "Gratis offerte",
    
    // Promo -30%
    "promo.discount": "-30%",
    "promo.until": "tot",
    "promo.date": "31/12/25",
    "promo.banner": "-30% tot 31/12/25 + 1 maand onderhoud gratis!",
    "promo.close": "Sluiten",
    "promo.badge": "Eerste Maand Onderhoud Gratis!",
    
    // Hero
    "hero.badge": "Guapo Web Designer",
    "hero.title": "Als je het kunt bedenken, kunnen wij het",
    "hero.title.highlight": "ontwerpen.",
    "hero.subtitle": "Websites ontworpen om uw zichtbaarheid te verbeteren en uw bedrijf te professionaliseren",
    "hero.cta.projects": "Bekijk onze projecten",
    "hero.cta.contact": "Neem contact op",
    
    // Announcement Banner
    "announcement.offer": "🎁 1 maand onderhoud gratis bij de creatie van elk site!",
    
    // About
    "about.title": "Over Guapo",
    "about.values.passion": "Passie",
    "about.values.passion.desc": "Elk project is een nieuw creatief avontuur",
    "about.values.innovation": "Innovatie",
    "about.values.innovation.desc": "Altijd voorop in de trends",
    "about.values.performance": "Prestatie",
    "about.values.performance.desc": "Snelle en geoptimaliseerde websites",
    "about.values.creativity": "Creativiteit",
    "about.values.creativity.desc": "Unieke en gedenkwaardige ontwerpen",
    "about.heading": "Gepassioneerde maker",
    "about.intro": "Gepassioneerd door design en nieuwe technologieën, creëren wij moderne, elegante en krachtige websites. Onze aanpak combineert creativiteit, technische expertise en aandacht voor detail om uw digitale projecten tot leven te brengen.",
    "about.intro.highlight": "",
    "about.intro.text": "",
    "about.p1": "Elk project is uniek en verdient bijzondere aandacht.",
    "about.p2.prefix": "",
    "about.p2.creativity": "",
    "about.p2.innovation": "",
    "about.p2.excellence": "",
    "about.p2.suffix": "",
    "about.badge.design": "🎨 UI/UX Design",
    "about.badge.performance": "⚡ Optimale prestaties",
    "about.badge.tech": "🚀 Moderne technologieën",
    
    // Services Page
    "services.page.title": "Onze Diensten",
    "services.desktop.title": "Desktop Showcase Sites",
    "services.desktop.desc": "Websites geoptimaliseerd voor grote schermen met professionele en moderne ontwerpen",
    "services.tablet.title": "Tablet Aanpassing",
    "services.tablet.desc": "Interfaces perfect aangepast aan tablets voor een vloeiende ervaring",
    "services.mobile.title": "Mobiele Optimalisatie",
    "services.mobile.desc": "Optimale navigatie op smartphones met maximale prestaties",
    "services.responsive.title": "Responsive Design",
    "services.responsive.desc": "Automatische aanpassing aan alle soorten apparaten en resoluties",
    "services.branding.title": "Visuele Identiteit",
    "services.branding.desc": "Creatie van logo's, grafische handvesten en unieke visuele elementen",
    "services.performance.title": "Web Prestaties",
    "services.performance.desc": "Ultrasnelle websites geoptimaliseerd voor SEO en gebruikerservaring",
    "services.cta.title": "Heeft u een showcase site nodig? 🚀",
    "services.cta.desc": "Restaurant, professioneel kantoor, bedrijf of persoonlijke portfolio: wij creëren uw showcase site toegankelijk op alle apparaten!",
    "services.cta.button": "Laten we praten over uw project 💬",
    
    // Services
    "services.title": "Onze",
    "services.title.highlight": "Diensten",
    "services.subtitle": "Wat wij voor u kunnen doen",
    "services.design.title": "UI/UX Design",
    "services.design.desc": "Creatie van intuïtieve en aantrekkelijke gebruikersinterfaces met een optimale ervaring.",
    "services.dev.title": "Web Ontwikkeling",
    "services.dev.desc": "Ontwikkeling van moderne websites met React, Next.js en de nieuwste technologieën.",
    
    // Portfolio
    "portfolio.title.prefix": "Port",
    "portfolio.title.highlight": "folio",
    "portfolio.subtitle": "Onze recente projecten",
    
    // Contact
    "contact.title": "Laten we",
    "contact.title.highlight": "Samenwerken",
    "contact.subtitle": "Heeft u een project in gedachten? Neem contact met ons op en laten we uw behoeften bespreken.",
    
    // Contact Page
    "contact.page.title": "Neem contact op",
    "contact.page.intro": "Heeft u een moderne en krachtige website nodig? Neem nu contact met ons op!",
    "contact.email.title": "Email",
    "contact.email.address": "info@guapowebdesigner.com",
    "contact.email.copy": "Kopiëren",
    "contact.email.copied": "Email gekopieerd!",
    "contact.instagram.title": "Instagram",
    "contact.instagram.handle": "@guapo.webdesigner",
    "contact.instagram.copy": "Kopiëren",
    "contact.instagram.copied": "Handle gekopieerd!",
    "contact.form.title": "Offerte aanvraag",
    "contact.form.name": "Volledige naam",
    "contact.form.email": "Email",
    "contact.form.phone": "Telefoon (optioneel)",
    "contact.form.message": "Bericht",
    "contact.form.submit": "Verstuur aanvraag",
    "contact.form.sending": "Bezig met versturen...",
    "contact.form.success": "Aanvraag succesvol verzonden!",
    "contact.form.error": "Fout bij verzenden. Probeer het opnieuw.",
    
    // Quote Page
    "quote.page.badge": "Gratis offerte binnen 48 uur",
    "quote.page.title": "Offerte",
    "quote.page.title.highlight": "Aanvraag",
    "quote.page.subtitle": "Vertel ons over uw project en ontvang een gepersonaliseerde offerte die is afgestemd op uw behoeften en budget.",
    "quote.page.card1.title": "Snel antwoord",
    "quote.page.card1.desc": "Offerte binnen 48 uur",
    "quote.page.card2.title": "Gratis offerte",
    "quote.page.card2.desc": "Zonder verplichting",
    "quote.page.card3.title": "Op maat",
    "quote.page.card3.desc": "Aangepast aan uw behoeften",
    "quote.page.cta.title": "Heeft u vragen voordat u uw aanvraag indient?",
    "quote.page.cta.desc": "Neem gerust rechtstreeks contact met ons op via e-mail of Instagram",
    
    // Quote Form - Step 1: Type Selection
    "quote.type.title": "Welk type project wilt u?",
    "quote.type.subtitle": "Kies het type site dat bij uw behoeften past",
    "quote.type.showcase": "Showcase Site",
    "quote.type.showcase.desc": "Presentatiewebsite voor uw bedrijf, portfolio of professionele activiteit",
    "quote.type.showcase.feature1": "Bedrijfspresentatie",
    "quote.type.showcase.feature2": "Professionele portfolio",
    "quote.type.showcase.feature3": "Contactformulieren",
    "quote.type.showcase.feature4": "Op maat gemaakt ontwerp",
    "quote.type.ecommerce": "E-commerce Site",
    "quote.type.ecommerce.desc": "Complete online winkel om uw producten of diensten online te verkopen",
    "quote.type.ecommerce.feature1": "Productcatalogus",
    "quote.type.ecommerce.feature2": "Winkelwagen & online betaling",
    "quote.type.ecommerce.feature3": "Bestellingsbeheer",
    "quote.type.ecommerce.feature4": "Klantaccounts",
    "quote.type.start": "Beginnen",
    
    // Quote Form - Step 2: Questions
    "quote.back": "Terug naar projecttype keuze",
    "quote.selected": "Geselecteerd projecttype:",
    "quote.showcase.pages": "Aantal pagina's van de showcase site",
    "quote.ecommerce.size": "Grootte van uw e-commerce winkel",
    "quote.ecommerce.small": "Kleine winkel (1-20 producten)",
    "quote.ecommerce.small.desc": "Ideaal om te starten met een beperkte selectie",
    "quote.ecommerce.medium": "Middelgrote winkel (21-100 producten)",
    "quote.ecommerce.medium.desc": "Voor een gediversifieerd productassortiment",
    "quote.ecommerce.large": "Grote winkel (100+ producten)",
    "quote.ecommerce.large.desc": "Complete catalogus met geavanceerd beheer",
    "quote.ecommerce.note": "De uiteindelijke prijs is afhankelijk van de hieronder geselecteerde e-commerce functionaliteiten",
    "quote.selected.label": "Geselecteerd type:",
    "quote.selected.size": "Geselecteerde grootte:",
    "quote.modify": "Wijzigen",
    "quote.features.ecommerce": "E-commerce Functionaliteiten",
    "quote.optimization.pack": "Alles Inclusief Pakket",
    "quote.optimization.pack.desc": "Inclusief alle essentiële optimalisaties voor een professionele en krachtige website",
    "quote.optimization.pack.seo": "Basis SEO",
    "quote.optimization.pack.performance": "Snelheidsoptimalisatie",
    "quote.optimization.pack.ssl": "SSL-certificaat/HTTPS",
    "quote.optimization.pack.gdpr": "AVG-naleving",
    "quote.optimization.recommended": "⭐ AANBEVOLEN",
    "quote.optimization.or": "of kies individueel",
    "quote.hosting.auto": "Hosting is automatisch inbegrepen in uw project.",
    
    // Quote Form
    "quote.success.title": "Bedankt voor uw aanvraag!",
    "quote.info.title": "Informatie",
    "quote.info.firstName": "Voornaam",
    "quote.info.firstNamePlaceholder": "Uw voornaam",
    "quote.info.lastName": "Achternaam",
    "quote.info.lastNamePlaceholder": "Uw achternaam",
    "quote.info.email": "Email",
    "quote.info.emailPlaceholder": "uw@email.com",
    "quote.info.company": "Bedrijfsnaam / Project",
    "quote.info.companyPlaceholder": "Naam van uw bedrijf of project",
    "quote.info.sector": "Sector (optioneel)",
    "quote.info.sectorPlaceholder": "Bv: Horeca, Diensten, etc.",
    "quote.siteType.title": "Type Website",
    "quote.siteType.simple": "Eenvoudige showcase site (1 tot 3 pagina's)",
    "quote.siteType.simpleDesc": "Ideaal om uw activiteit te presenteren met de essentiële pagina's",
    "quote.siteType.standard": "Standaard showcase site (4 tot 5 pagina's)",
    "quote.siteType.standardDesc": "Voor een complete webpresentie met meer inhoud",
    "quote.siteType.advanced": "Geavanceerde showcase site (6 tot 8 pagina's)",
    "quote.siteType.advancedDesc": "Voor een gedetailleerde presentatie van uw bedrijf",
    "quote.siteType.premium": "Premium showcase site (9 tot 12 pagina's)",
    "quote.siteType.premiumDesc": "Voor een complete site met alle nodige informatie",
    "quote.siteType.portfolio": "Portfolio / persoonlijke site",
    "quote.siteType.portfolioDesc": "Laat uw prestaties en expertise zien",
    "quote.siteType.ecommerce": "E-commerce site",
    "quote.siteType.ecommerceDesc": "Complete online winkel met product- en betalingsbeheer",
    "quote.design.title": "Design & Inhoud",
    "quote.design.custom": "Op maat gemaakt design (gepersonaliseerde UX/UI) - Inbegrepen",
    "quote.design.responsive": "Responsive (mobiel + tablet + computer) - Inbegrepen",
    "quote.design.pageCount": "Verwacht aantal pagina's",
    "quote.design.pageCountPlaceholder": "Bv: 5",
    "quote.features.title": "Functionaliteiten / Modules",
    "quote.features.contactForm": "Eenvoudig contactformulier",
    "quote.features.quoteForm": "Offerteaanvraagformulier",
    "quote.features.autoEmailsQuote": "Automatisch verzenden van bevestigingsmails (voor offerte)",
    "quote.features.booking": "Online afspraaksysteem (met automatische e-mails)",
    "quote.features.calendar": "Toevoegen aan agenda (Google Agenda, Outlook, ICS, etc.)",
    "quote.features.multilingual": "Meertalig",
    "quote.features.selectLanguages": "Selecteer de gewenste talen:",
    "quote.features.otherLanguage": "Andere taal",
    "quote.features.otherLanguagePlaceholder": "Bv: Spaans, Italiaans, Duits...",
    "quote.features.productCatalog": "Productcatalogus",
    "quote.features.shoppingCart": "Winkelwagen",
    "quote.features.paymentGateway": "Betaalgateway (Stripe, PayPal, etc.)",
    "quote.features.orderManagement": "Bestellingsbeheer",
    "quote.features.inventoryManagement": "Voorraadbeheer",
    "quote.features.customerAccounts": "Klantaccounts",
    "quote.optimization.title": "Optimalisatie & Beveiliging",
    "quote.optimization.seo": "Basis SEO (tags, titels, URLs)",
    "quote.optimization.performance": "Snelheids- / prestatieoptimalisatie",
    "quote.optimization.ssl": "SSL-certificaat / HTTPS",
    "quote.optimization.gdpr": "AVG / wettelijke naleving",
    "quote.hosting.title": "Hosting",
    "quote.hosting.hosting": "Hosting",
    "quote.hosting.domain": "Domeinnaam",
    "quote.hosting.selectOption": "Selecteer een optie",
    "quote.hosting.included": "Inbegrepen in het project",
    "quote.hosting.clientProvided": "Verstrekt door de klant",
    "quote.hosting.toDiscuss": "Te bespreken",
    "quote.message.title": "Specifieke opmerkingen / Bijzondere behoeften",
    "quote.message.label": "Gedetailleerde beschrijving van uw project",
    "quote.message.placeholder": "Beschrijf uw project in detail: uw doelstellingen, uw doelgroep, uw specifieke behoeften, voorbeelden van sites die u leuk vindt, bijzondere beperkingen, etc.",
    "quote.gdpr.title": "AVG-toestemming",
    "quote.gdpr.text": "Ik ga ermee akkoord dat mijn persoonlijke gegevens worden verzameld en verwerkt door GUAPO Web Designer om mijn offerteaanvraag te verwerken. Mijn gegevens worden nooit aan derden verkocht. Ik kan mijn rechten uitoefenen (toegang, rectificatie, verwijdering) door contact op te nemen met",
    "quote.gdpr.moreInfo": "Voor meer informatie, raadpleeg ons",
    "quote.gdpr.privacyPolicy": "privacybeleid",
    "quote.submit.button": "Mijn offerteaanvraag verzenden",
    "quote.submit.sending": "Bezig met verzenden...",
    "quote.submit.required": "* Verplichte velden",
    
    "footer.description": "Maker van moderne en krachtige websites. Uw visie, onze expertise.",
    "footer.links": "Snelle links",
    "footer.legal": "Informations légales",
    "footer.privacy": "Politique de confidentialité",
    "footer.legal.terms": "Mentions légales",
    "footer.social": "Volg ons",
    "footer.copyright": "Guapo Web Designer 2025",
    "footer.rights": "Alle rechten voorbehouden."
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.portfolio": "Portfolio",
    "nav.contact": "Contact",
    "nav.quote": "Free Quote",
    
    // Promo -30%
    "promo.discount": "-30%",
    "promo.until": "until",
    "promo.date": "31/12/25",
    "promo.banner": "-30% until 31/12/25 + 1 month of maintenance free!",
    "promo.close": "Close",
    "promo.badge": "First Month of Maintenance Free!",
    
    // Hero
    "hero.badge": "Guapo Web Designer",
    "hero.title": "If you can imagine it, we can",
    "hero.title.highlight": "design it.",
    "hero.subtitle": "Websites designed to improve your visibility and professionalize your business",
    "hero.cta.projects": "View our projects",
    "hero.cta.contact": "Contact us",
    
    // Announcement Banner
    "announcement.offer": "🎁 1 month of maintenance included with every site creation!",
    
    // About
    "about.title": "About Guapo",
    "about.values.passion": "Passion",
    "about.values.passion.desc": "Every project is a new creative adventure",
    "about.values.innovation": "Innovation",
    "about.values.innovation.desc": "Always at the forefront of trends",
    "about.values.performance": "Performance",
    "about.values.performance.desc": "Fast and optimized websites",
    "about.values.creativity": "Creativity",
    "about.values.creativity.desc": "Unique and memorable designs",
    "about.heading": "Passionate creator",
    "about.intro": "Passionate about design and new technologies, we create modern, elegant and powerful websites. Our approach combines creativity, technical expertise and attention to detail to bring your digital projects to life.",
    "about.intro.highlight": "",
    "about.intro.text": "",
    "about.p1": "Each project is unique and deserves special attention.",
    "about.p2.prefix": "",
    "about.p2.creativity": "",
    "about.p2.innovation": "",
    "about.p2.excellence": "",
    "about.p2.suffix": "",
    "about.badge.design": "🎨 UI/UX Design",
    "about.badge.performance": "⚡ Optimal performance",
    "about.badge.tech": "🚀 Modern technologies",
    
    // Services Page
    "services.page.title": "Our Services",
    "services.desktop.title": "Desktop Showcase Sites",
    "services.desktop.desc": "Websites optimized for large screens with professional and modern designs",
    "services.tablet.title": "Tablet Adaptation",
    "services.tablet.desc": "Interfaces perfectly adapted to tablets for a smooth experience",
    "services.mobile.title": "Mobile Optimization",
    "services.mobile.desc": "Optimal navigation on smartphones with maximum performance",
    "services.responsive.title": "Responsive Design",
    "services.responsive.desc": "Automatic adaptation to all types of devices and resolutions",
    "services.branding.title": "Visual Identity",
    "services.branding.desc": "Creation of logos, graphic guidelines and unique visual elements",
    "services.performance.title": "Web Performance",
    "services.performance.desc": "Ultra-fast websites optimized for SEO and user experience",
    "services.cta.title": "Need a showcase website? 🚀",
    "services.cta.desc": "Restaurant, professional office, company or personal portfolio: we create your showcase website accessible on all devices!",
    "services.cta.button": "Let's discuss your project 💬",
    
    // Services
    "services.title": "Our",
    "services.title.highlight": "Services",
    "services.subtitle": "What we can do for you",
    "services.design.title": "UI/UX Design",
    "services.design.desc": "Creation of intuitive and attractive user interfaces with an optimal experience.",
    "services.dev.title": "Web Development",
    "services.dev.desc": "Development of modern websites with React, Next.js and the latest technologies.",
    
    // Portfolio
    "portfolio.title.prefix": "Port",
    "portfolio.title.highlight": "folio",
    "portfolio.subtitle": "Our recent projects",
    
    // Contact
    "contact.title": "Let's Work",
    "contact.title.highlight": "Together",
    "contact.subtitle": "Have a project in mind? Contact us and let's discuss your needs.",
    
    // Contact Page
    "contact.page.title": "Contact Us",
    "contact.page.intro": "Need a modern and powerful website? Contact us now!",
    "contact.email.title": "Email",
    "contact.email.address": "info@guapowebdesigner.com",
    "contact.email.copy": "Copy",
    "contact.email.copied": "Email copied!",
    "contact.instagram.title": "Instagram",
    "contact.instagram.handle": "@guapo.webdesigner",
    "contact.instagram.copy": "Copy",
    "contact.instagram.copied": "Handle copied!",
    "contact.form.title": "Quote Request",
    "contact.form.name": "Full Name",
    "contact.form.email": "Email",
    "contact.form.phone": "Phone (optional)",
    "contact.form.message": "Message",
    "contact.form.submit": "Send Request",
    "contact.form.sending": "Sending...",
    "contact.form.success": "Request sent successfully!",
    "contact.form.error": "Error sending. Please try again.",
    
    // Quote Page
    "quote.page.badge": "Free quote within 48 hours",
    "quote.page.title": "Quote",
    "quote.page.title.highlight": "Request",
    "quote.page.subtitle": "Tell us about your project and receive a personalized quote tailored to your needs and budget.",
    "quote.page.card1.title": "Fast response",
    "quote.page.card1.desc": "Quote within 48 hours",
    "quote.page.card2.title": "Free quote",
    "quote.page.card2.desc": "No commitment",
    "quote.page.card3.title": "Custom-made",
    "quote.page.card3.desc": "Tailored to your needs",
    "quote.page.cta.title": "Questions before submitting your request?",
    "quote.page.cta.desc": "Feel free to contact us directly by email or Instagram",
    
    // Quote Form - Step 1: Type Selection
    "quote.type.title": "What type of project do you want?",
    "quote.type.subtitle": "Choose the type of site that suits your needs",
    "quote.type.showcase": "Showcase Website",
    "quote.type.showcase.desc": "Presentation website for your business, portfolio, or professional activity",
    "quote.type.showcase.feature1": "Business presentation",
    "quote.type.showcase.feature2": "Professional portfolio",
    "quote.type.showcase.feature3": "Contact forms",
    "quote.type.showcase.feature4": "Custom design",
    "quote.type.ecommerce": "E-commerce Website",
    "quote.type.ecommerce.desc": "Complete online store to sell your products or services online",
    "quote.type.ecommerce.feature1": "Product catalog",
    "quote.type.ecommerce.feature2": "Shopping cart & online payment",
    "quote.type.ecommerce.feature3": "Order management",
    "quote.type.ecommerce.feature4": "Customer accounts",
    "quote.type.start": "Start",
    
    // Quote Form - Step 2: Questions
    "quote.back": "Back to project type selection",
    "quote.selected": "Selected project type:",
    "quote.showcase.pages": "Number of pages for the showcase website",
    "quote.ecommerce.size": "Size of your e-commerce store",
    "quote.ecommerce.small": "Small store (1-20 products)",
    "quote.ecommerce.small.desc": "Ideal to start with a limited selection",
    "quote.ecommerce.medium": "Medium store (21-100 products)",
    "quote.ecommerce.medium.desc": "For a diversified product range",
    "quote.ecommerce.large": "Large store (100+ products)",
    "quote.ecommerce.large.desc": "Complete catalog with advanced management",
    "quote.ecommerce.note": "The final price will depend on the e-commerce features selected below",
    "quote.selected.label": "Selected type:",
    "quote.selected.size": "Selected size:",
    "quote.modify": "Edit",
    "quote.features.ecommerce": "E-commerce Features",
    "quote.optimization.pack": "All-Inclusive Package",
    "quote.optimization.pack.desc": "Includes all essential optimizations for a professional and powerful website",
    "quote.optimization.pack.seo": "Basic SEO",
    "quote.optimization.pack.performance": "Speed optimization",
    "quote.optimization.pack.ssl": "SSL certificate/HTTPS",
    "quote.optimization.pack.gdpr": "GDPR compliance",
    "quote.optimization.recommended": "⭐ RECOMMENDED",
    "quote.optimization.or": "or choose individually",
    "quote.hosting.auto": "Hosting is automatically included in your project.",
    
    // Quote Form
    "quote.success.title": "Thank you for your request!",
    "quote.info.title": "Information",
    "quote.info.firstName": "First Name",
    "quote.info.firstNamePlaceholder": "Your first name",
    "quote.info.lastName": "Last Name",
    "quote.info.lastNamePlaceholder": "Your last name",
    "quote.info.email": "Email",
    "quote.info.emailPlaceholder": "your@email.com",
    "quote.info.company": "Company / Project Name",
    "quote.info.companyPlaceholder": "Name of your company or project",
    "quote.info.sector": "Business Sector (optional)",
    "quote.info.sectorPlaceholder": "E.g.: Restaurant, Services, etc.",
    "quote.siteType.title": "Website Type",
    "quote.siteType.simple": "Simple showcase site (1 to 3 pages)",
    "quote.siteType.simpleDesc": "Ideal for presenting your activity with essential pages",
    "quote.siteType.standard": "Standard showcase site (4 to 5 pages)",
    "quote.siteType.standardDesc": "For a complete web presence with more content",
    "quote.siteType.advanced": "Advanced showcase site (6 to 8 pages)",
    "quote.siteType.advancedDesc": "For a detailed presentation of your company",
    "quote.siteType.premium": "Premium showcase site (9 to 12 pages)",
    "quote.siteType.premiumDesc": "For a complete website with all necessary information",
    "quote.siteType.portfolio": "Portfolio / personal site",
    "quote.siteType.portfolioDesc": "Showcase your achievements and expertise",
    "quote.siteType.ecommerce": "E-commerce site",
    "quote.siteType.ecommerceDesc": "Complete online store with product and payment management",
    "quote.design.title": "Design & Content",
    "quote.design.custom": "Custom design (personalized UX/UI) - Included",
    "quote.design.responsive": "Responsive (mobile + tablet + desktop) - Included",
    "quote.design.pageCount": "Expected number of pages",
    "quote.design.pageCountPlaceholder": "E.g.: 5",
    "quote.features.title": "Features / Modules",
    "quote.features.contactForm": "Simple contact form",
    "quote.features.quoteForm": "Quote request form",
    "quote.features.autoEmailsQuote": "Automatic confirmation emails (for quotes)",
    "quote.features.booking": "Online booking system (with automatic emails)",
    "quote.features.calendar": "Add to calendar (Google Calendar, Outlook, ICS, etc.)",
    "quote.features.multilingual": "Multilingual",
    "quote.features.selectLanguages": "Select desired languages:",
    "quote.features.otherLanguage": "Other language",
    "quote.features.otherLanguagePlaceholder": "E.g: Spanish, Italian, German...",
    "quote.features.productCatalog": "Product catalog",
    "quote.features.shoppingCart": "Shopping cart",
    "quote.features.paymentGateway": "Payment gateway (Stripe, PayPal, etc.)",
    "quote.features.orderManagement": "Order management",
    "quote.features.inventoryManagement": "Inventory management",
    "quote.features.customerAccounts": "Customer accounts",
    "quote.optimization.title": "Optimization & Security",
    "quote.optimization.seo": "Basic SEO (tags, titles, URLs)",
    "quote.optimization.performance": "Speed / performance optimization",
    "quote.optimization.ssl": "SSL certificate / HTTPS",
    "quote.optimization.gdpr": "GDPR / legal compliance",
    "quote.hosting.title": "Hosting",
    "quote.hosting.hosting": "Hosting",
    "quote.hosting.domain": "Domain name",
    "quote.hosting.selectOption": "Select an option",
    "quote.hosting.included": "Included in the project",
    "quote.hosting.clientProvided": "Provided by the client",
    "quote.hosting.toDiscuss": "To discuss",
    "quote.message.title": "Specific Remarks / Special Needs",
    "quote.message.label": "Detailed description of your project",
    "quote.message.placeholder": "Describe your project in detail: your objectives, your target audience, your specific needs, examples of sites you like, particular constraints, etc.",
    "quote.gdpr.title": "GDPR Consent",
    "quote.gdpr.text": "I agree that my personal data will be collected and processed by GUAPO Web Designer for the purpose of processing my quote request. My data will never be sold to third parties. I can exercise my rights (access, rectification, deletion) by contacting",
    "quote.gdpr.moreInfo": "For more information, please consult our",
    "quote.gdpr.privacyPolicy": "privacy policy",
    "quote.submit.button": "Send my quote request",
    "quote.submit.sending": "Sending...",
    "quote.submit.required": "* Required fields",
    
    "footer.description": "Creator of modern and powerful websites. Your vision, our expertise.",
    "footer.links": "Quick Links",
    "footer.legal": "Legal Information",
    "footer.privacy": "Privacy Policy",
    "footer.legal.terms": "Terms and Conditions",
    "footer.social": "Follow Us",
    "footer.copyright": "Guapo Web Designer 2025",
    "footer.rights": "All rights reserved."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("fr");

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.fr] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}